"""
services/llm_service.py
========================
OpenAI Responses API wrapper.

Uses the CURRENT OpenAI Python SDK (openai >= 1.0) with the Responses API
and structured JSON schema output for indicator extraction.

Key design decisions:
- Structured output (response_format / JSON schema) makes extraction
  machine-validated, not dependent on prose formatting.
- Temperature = 0 for deterministic extraction.
- The LLM NEVER makes routing decisions — it only extracts and summarises.
- If the API call fails, a controlled degraded state is returned;
  the workflow continues in demo/deterministic mode.
- The API key is NEVER logged, printed, or returned.
"""
from __future__ import annotations

import json
import logging
from typing import Any

from models.schemas import (
    IndicatorExtractionResult,
    EvidenceSummaryResult,
    ExtractedIndicator,
)
from utils.config import get_openai_key, get_openai_model, is_demo_mode

logger = logging.getLogger(__name__)

# ── Demo-mode fallback responses ──────────────────────────────────────────────
_DEMO_EXTRACTION: dict[str, Any] = {
    "indicators": [],
    "ambiguities": [],
    "note": "Demo mode — no API key configured. Deterministic keyword matching used.",
}

_DEMO_SUMMARY: dict[str, Any] = {
    "summary": (
        "Demo mode: this summary would be generated by the language model "
        "when an API key is configured. The reported information has been "
        "processed through deterministic indicator matching."
    ),
    "missing_information": [],
}


# ── System prompts ─────────────────────────────────────────────────────────────
_EXTRACTION_SYSTEM = """
You are a structured data extraction assistant supporting a human reviewer.
Your role is to identify possible trafficking-related indicators from a case narrative.

IMPORTANT CONSTRAINTS:
- You MUST NOT conclude that trafficking has occurred.
- You MUST NOT identify or name perpetrators.
- You MUST NOT predict criminality or assess guilt.
- You MUST NOT use race, ethnicity, nationality, immigration status, sex, religion,
  or other protected characteristics as escalation criteria.
- You MUST NOT generate a risk probability or numerical score.
- If you are uncertain, use confidence=POSSIBLE or INFERRED — not REPORTED.
- Only extract indicators explicitly supported by the narrative text.
- Use "individual" or "person", not "victim" or "trafficker".
- If no indicators are present, return an empty indicators list.

Return your response as valid JSON matching the provided schema exactly.
""".strip()

_SUMMARY_SYSTEM = """
You are a neutral evidence-summary assistant supporting a human reviewer.
Write a brief, hedged summary of the reported indicators for the reviewer.

IMPORTANT CONSTRAINTS:
- Do NOT state that trafficking has occurred.
- Do NOT name or accuse anyone of being a trafficker.
- Do NOT give a probability or risk score.
- Use "individual" or "person", not "victim".
- Use hedged language: "reported", "alleged", "as described".
- The summary must be ≤400 characters.
- If there are no indicators, say so clearly.
- List 0–5 key information gaps that would assist the reviewer.

Return your response as valid JSON matching the provided schema exactly.
""".strip()


# ── OpenAI client (lazy-initialised) ─────────────────────────────────────────
_client = None


def _get_client():
    global _client
    if _client is None:
        from openai import OpenAI
        key = get_openai_key()
        if not key:
            raise RuntimeError("No OpenAI API key configured.")
        _client = OpenAI(api_key=key)
    return _client


def _reset_client():
    """Reset the cached client (useful for testing)."""
    global _client
    _client = None


# ── Indicator extraction ──────────────────────────────────────────────────────

def extract_indicators_llm(masked_narrative: str) -> IndicatorExtractionResult:
    """
    Call the OpenAI Responses API to extract trafficking-related indicators
    from a PII-masked case narrative.

    Returns an IndicatorExtractionResult.
    On API failure, returns an empty result with a failure note.
    Never raises — workflow continues in degraded mode.
    """
    if is_demo_mode() or not masked_narrative.strip():
        return IndicatorExtractionResult(**_DEMO_EXTRACTION)

    schema = IndicatorExtractionResult.model_json_schema()

    try:
        client = _get_client()
        model = get_openai_model()
        response = client.responses.create(
            model=model,
            instructions=_EXTRACTION_SYSTEM,
            input=f"Case narrative (PII has been masked):\n\n{masked_narrative}",
            text={
                "format": {
                    "type": "json_schema",
                    "name": "indicator_extraction",
                    "schema": schema,
                    "strict": True,
                }
            },
            temperature=0,
        )
        raw = response.output_text
        data = json.loads(raw)
        return IndicatorExtractionResult(**data)

    except Exception as exc:
        logger.warning("LLM indicator extraction failed: %s", type(exc).__name__)
        return IndicatorExtractionResult(
            indicators=[],
            ambiguities=[],
            note=f"LLM extraction unavailable ({type(exc).__name__}). Deterministic matching used.",
        )


# ── Evidence summary ──────────────────────────────────────────────────────────

def generate_evidence_summary(
    masked_narrative: str,
    indicator_hits: list[dict],
    routing_state: str,
) -> EvidenceSummaryResult:
    """
    Call the OpenAI Responses API to generate a hedged evidence summary
    for the human reviewer.

    Returns an EvidenceSummaryResult.
    On API failure, returns a safe fallback summary.
    Never raises.
    """
    if is_demo_mode():
        n = len(indicator_hits)
        summary = (
            f"Demo mode: {n} indicator category(ies) identified through "
            f"deterministic matching. Routing recommendation: "
            f"{routing_state.replace('_', ' ')}. "
            "This is decision-support only — not a trafficking determination."
        )
        return EvidenceSummaryResult(summary=summary[:600], missing_information=[])

    indicator_text = "\n".join(
        f"- {h.get('label', h.get('category', '?'))} "
        f"[{h.get('confidence', '?')}] — {h.get('evidence_quote', 'No quote available')}"
        for h in indicator_hits
    ) or "None identified."

    user_message = (
        f"Routing recommendation: {routing_state}\n\n"
        f"Identified indicators:\n{indicator_text}\n\n"
        f"Narrative excerpt (PII masked):\n{masked_narrative[:1500]}"
    )

    schema = EvidenceSummaryResult.model_json_schema()

    try:
        client = _get_client()
        model = get_openai_model()
        response = client.responses.create(
            model=model,
            instructions=_SUMMARY_SYSTEM,
            input=user_message,
            text={
                "format": {
                    "type": "json_schema",
                    "name": "evidence_summary",
                    "schema": schema,
                    "strict": True,
                }
            },
            temperature=0,
        )
        data = json.loads(response.output_text)
        result = EvidenceSummaryResult(**data)

        # Post-generation safety check — belt and suspenders
        prohibited = [
            "confirmed trafficking", "is a trafficker", "is guilty",
            "has been trafficked", "trafficking confirmed",
        ]
        for term in prohibited:
            if term.lower() in result.summary.lower():
                result.summary = result.summary.replace(term, "[term redacted]")

        return result

    except Exception as exc:
        logger.warning("LLM evidence summary failed: %s", type(exc).__name__)
        n = len(indicator_hits)
        return EvidenceSummaryResult(
            summary=(
                f"{n} indicator category(ies) identified. "
                f"Routing recommendation: {routing_state.replace('_', ' ')}. "
                "Evidence summary unavailable due to API error. "
                "Human reviewer should assess the reported indicators directly."
            )[:600],
            missing_information=[],
        )
